name: MyWarpMenu
main: com.shawlyne.mc.MyWarpMenu.MyWarpMenu
version: 0.1
commands:
  warpmenu:
    description: Nice menu of warps available through MyWarp
    usage: /warpmenu
  wm:
    description: (Short-cut) Nice menu of warps available through MyWarp
    usage: /wm